/*
 * Collection payments
 * <img src=\"https://devtest.baokim.vn/collection/core_ctt/image/Picture1.png\" class=\"image-collection-payment\" /> <p><strong>Note:</strong></p> <p>+ In case PARTNER want to use collect via Virtual Account, PARTNER will need to buid:</p> <p style=\"padding-left: 50px;\">     - <a href=\"#operations-Virtual_Account_4\\.0-8442c69ffbaf4b3677a52fa3ebcef6d4\">Register virtual account</a> <br>     - <a href=\"#operations-Virtual_Account_4\\.0-1796c61005edee3976097a607fe9dbaa\">Update virtual account informations</a> <br>     - <a href=\"#operations-tag-Notice_of_collection_transaction\">Notice of collection transaction</a> <br> </p>
 *
 * OpenAPI spec version: 2.3 and 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * V4CreateBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-30T01:31:18.186Z[Etc/UTC]")
public class V4CreateBody {
  @SerializedName("RequestId")
  private String requestId = null;

  @SerializedName("RequestTime")
  private String requestTime = null;

  @SerializedName("PartnerCode")
  private String partnerCode = null;

  @SerializedName("AccName")
  private String accName = null;

  @SerializedName("CollectAmount")
  private BigDecimal collectAmount = null;

  @SerializedName("OrderId")
  private String orderId = null;

  @SerializedName("ExpireDate")
  private String expireDate = null;

  @SerializedName("Bank")
  private String bank = null;

  public V4CreateBody requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Unique code 
   * @return requestId
  **/
  @Schema(example = "BK16321291688141", description = "Unique code ")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public V4CreateBody requestTime(String requestTime) {
    this.requestTime = requestTime;
    return this;
  }

   /**
   * Time send the request from PARTNER , format: YYYY-MM-DD HH:MM:SS.
   * @return requestTime
  **/
  @Schema(example = "2022-01-24 10:59:46", description = "Time send the request from PARTNER , format: YYYY-MM-DD HH:MM:SS.")
  public String getRequestTime() {
    return requestTime;
  }

  public void setRequestTime(String requestTime) {
    this.requestTime = requestTime;
  }

  public V4CreateBody partnerCode(String partnerCode) {
    this.partnerCode = partnerCode;
    return this;
  }

   /**
   * Unique code BAOKIM provide
   * @return partnerCode
  **/
  @Schema(example = "CHIHOBAOKIM", description = "Unique code BAOKIM provide")
  public String getPartnerCode() {
    return partnerCode;
  }

  public void setPartnerCode(String partnerCode) {
    this.partnerCode = partnerCode;
  }

  public V4CreateBody accName(String accName) {
    this.accName = accName;
    return this;
  }

   /**
   * The name of Account holder (name of USER)
   * @return accName
  **/
  @Schema(example = "NHU ANH", description = "The name of Account holder (name of USER)")
  public String getAccName() {
    return accName;
  }

  public void setAccName(String accName) {
    this.accName = accName;
  }

  public V4CreateBody collectAmount(BigDecimal collectAmount) {
    this.collectAmount = collectAmount;
    return this;
  }

   /**
   * collect amount 
   * @return collectAmount
  **/
  @Schema(example = "50000", description = "collect amount ")
  public BigDecimal getCollectAmount() {
    return collectAmount;
  }

  public void setCollectAmount(BigDecimal collectAmount) {
    this.collectAmount = collectAmount;
  }

  public V4CreateBody orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Unique id for each VA
   * @return orderId
  **/
  @Schema(example = "BK1632129167822619", description = "Unique id for each VA")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public V4CreateBody expireDate(String expireDate) {
    this.expireDate = expireDate;
    return this;
  }

   /**
   * Expire date. Format: YYYYMM-DD HH:II:SS
   * @return expireDate
  **/
  @Schema(example = "2023-09-20 16:12:46", description = "Expire date. Format: YYYYMM-DD HH:II:SS")
  public String getExpireDate() {
    return expireDate;
  }

  public void setExpireDate(String expireDate) {
    this.expireDate = expireDate;
  }

  public V4CreateBody bank(String bank) {
    this.bank = bank;
    return this;
  }

   /**
   * Bank
   * @return bank
  **/
  @Schema(example = "WOORIBANK", description = "Bank")
  public String getBank() {
    return bank;
  }

  public void setBank(String bank) {
    this.bank = bank;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V4CreateBody v4CreateBody = (V4CreateBody) o;
    return Objects.equals(this.requestId, v4CreateBody.requestId) &&
        Objects.equals(this.requestTime, v4CreateBody.requestTime) &&
        Objects.equals(this.partnerCode, v4CreateBody.partnerCode) &&
        Objects.equals(this.accName, v4CreateBody.accName) &&
        Objects.equals(this.collectAmount, v4CreateBody.collectAmount) &&
        Objects.equals(this.orderId, v4CreateBody.orderId) &&
        Objects.equals(this.expireDate, v4CreateBody.expireDate) &&
        Objects.equals(this.bank, v4CreateBody.bank);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, requestTime, partnerCode, accName, collectAmount, orderId, expireDate, bank);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V4CreateBody {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    requestTime: ").append(toIndentedString(requestTime)).append("\n");
    sb.append("    partnerCode: ").append(toIndentedString(partnerCode)).append("\n");
    sb.append("    accName: ").append(toIndentedString(accName)).append("\n");
    sb.append("    collectAmount: ").append(toIndentedString(collectAmount)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    expireDate: ").append(toIndentedString(expireDate)).append("\n");
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
