/* 
 *  Installment docs API
 *
 * <a href='/baokim-firm-open-api-9050'>1: Function Check Installment Support </a>  <a href='/baokim-firm-open-api-9051'>2: Function Get Bank Loan Package </a>  <a href='/baokim-firm-open-api-9052'>3: Function Create Transaction </a>  <a href='/baokim-firm-open-api-9062'>4: Function Cancel order</a>  Private key and public key Baokim is currently using digital signature by RSA-SHA1  There are several ways to generate RSA key pairs.  Way 1:  Generate your RSA key pairs online: <a href=\"http://travistidwell.com/blog/2013/09/06/an-online-rsa-public-and-private-key-generator/\" target=\"_blank\">Generate now</a>  Way 2:  Using OpenSSL software for Windows:  Step 1: Download the software at:  http://slproweb.com/products/Win32OpenSSL.html. Partner should download the installer \"OpenSSL_Light-1_0_2k\". Then install in any directory, for example \"C:\\OpenSSLWin64\"  Step 2: Access \"C:\\OpenSSLWin64\\bin\" then open the command prompt. Type the command to declare the environment config.  set OPENSSL_CONF=C:\\OpenSSL-Win64\\bin\\openssl.cfg  Step 3: Generate private key and public key  openssl genrsa -aes256 -out c:\\opensslkeys\\partner\\partner_privatekey.pem 2048  openssl rsa –in c:\\opensslkeys\\partner\\partner_privatekey.pem -pubout >c:\\opensslkeys\\partner\\partner_publickey.pem  After successful pairing, Partner will send back to Baokim the public key to authenticate the signature that the Partner sends via the API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse2001DataLoanPackages
    /// </summary>
    [DataContract]
        public partial class InlineResponse2001DataLoanPackages :  IEquatable<InlineResponse2001DataLoanPackages>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2001DataLoanPackages" /> class.
        /// </summary>
        /// <param name="loanPackId">loanPackId.</param>
        /// <param name="packageName">packageName.</param>
        /// <param name="gracePeriod">gracePeriod.</param>
        /// <param name="conversionFee">conversionFee.</param>
        public InlineResponse2001DataLoanPackages(string loanPackId = default(string), string packageName = default(string), string gracePeriod = default(string), string conversionFee = default(string))
        {
            this.LoanPackId = loanPackId;
            this.PackageName = packageName;
            this.GracePeriod = gracePeriod;
            this.ConversionFee = conversionFee;
        }
        
        /// <summary>
        /// Gets or Sets LoanPackId
        /// </summary>
        [DataMember(Name="LoanPackId", EmitDefaultValue=false)]
        public string LoanPackId { get; set; }

        /// <summary>
        /// Gets or Sets PackageName
        /// </summary>
        [DataMember(Name="PackageName", EmitDefaultValue=false)]
        public string PackageName { get; set; }

        /// <summary>
        /// Gets or Sets GracePeriod
        /// </summary>
        [DataMember(Name="GracePeriod", EmitDefaultValue=false)]
        public string GracePeriod { get; set; }

        /// <summary>
        /// Gets or Sets ConversionFee
        /// </summary>
        [DataMember(Name="ConversionFee", EmitDefaultValue=false)]
        public string ConversionFee { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2001DataLoanPackages {\n");
            sb.Append("  LoanPackId: ").Append(LoanPackId).Append("\n");
            sb.Append("  PackageName: ").Append(PackageName).Append("\n");
            sb.Append("  GracePeriod: ").Append(GracePeriod).Append("\n");
            sb.Append("  ConversionFee: ").Append(ConversionFee).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse2001DataLoanPackages);
        }

        /// <summary>
        /// Returns true if InlineResponse2001DataLoanPackages instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse2001DataLoanPackages to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2001DataLoanPackages input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LoanPackId == input.LoanPackId ||
                    (this.LoanPackId != null &&
                    this.LoanPackId.Equals(input.LoanPackId))
                ) && 
                (
                    this.PackageName == input.PackageName ||
                    (this.PackageName != null &&
                    this.PackageName.Equals(input.PackageName))
                ) && 
                (
                    this.GracePeriod == input.GracePeriod ||
                    (this.GracePeriod != null &&
                    this.GracePeriod.Equals(input.GracePeriod))
                ) && 
                (
                    this.ConversionFee == input.ConversionFee ||
                    (this.ConversionFee != null &&
                    this.ConversionFee.Equals(input.ConversionFee))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LoanPackId != null)
                    hashCode = hashCode * 59 + this.LoanPackId.GetHashCode();
                if (this.PackageName != null)
                    hashCode = hashCode * 59 + this.PackageName.GetHashCode();
                if (this.GracePeriod != null)
                    hashCode = hashCode * 59 + this.GracePeriod.GetHashCode();
                if (this.ConversionFee != null)
                    hashCode = hashCode * 59 + this.ConversionFee.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
