/*
 * Example for response examples value
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CollectionV2Body;
import io.swagger.client.model.InlineResponse101;
import io.swagger.client.model.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for VirtualAccountApi
 */
@Ignore
public class VirtualAccountApiTest {

    private final VirtualAccountApi api = new VirtualAccountApi();

    /**
     * create &amp; update va
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void 6ce3bcd0268f76548ace52ed5eeeefefTest() throws Exception {
        CollectionV2Body body = null;
        String contentType = null;
        String signature = null;
        InlineResponse200 response = api.6ce3bcd0268f76548ace52ed5eeeefef(body, contentType, signature);

        // TODO: test validations
    }
}
