# coding: utf-8

# flake8: noqa
"""
    Example for response examples value

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.collection_v2_body import CollectionV2Body
from swagger_client.models.inline_response101 import InlineResponse101
from swagger_client.models.inline_response200 import InlineResponse200
