/* 
 * Collection payments
 *
 * <img src=\"https://devtest.baokim.vn/collection/core_ctt/image/Picture1.png\" class=\"image-collection-payment\" /> <p><strong>Note:</strong></p> <p>+ In case PARTNER want to use collect via Virtual Account, PARTNER will need to buid:</p> <p style=\"padding-left: 50px;\">     - <a href=\"#operations-Virtual_Account_4\\.0-8442c69ffbaf4b3677a52fa3ebcef6d4\">Register virtual account</a> <br>     - <a href=\"#operations-Virtual_Account_4\\.0-1796c61005edee3976097a607fe9dbaa\">Update virtual account informations</a> <br>     - <a href=\"#operations-tag-Notice_of_collection_transaction\">Notice of collection transaction</a> <br> </p>
 *
 * OpenAPI spec version: 2.3 and 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BodyTests
    {
        // TODO uncomment below to declare an instance variable for Body
        //private Body instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body
            //instance = new Body();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body
        /// </summary>
        [Test]
        public void BodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body
            //Assert.IsInstanceOfType<Body> (instance, "variable 'instance' is a Body");
        }


        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'RequestTime'
        /// </summary>
        [Test]
        public void RequestTimeTest()
        {
            // TODO unit test for the property 'RequestTime'
        }
        /// <summary>
        /// Test the property 'PartnerCode'
        /// </summary>
        [Test]
        public void PartnerCodeTest()
        {
            // TODO unit test for the property 'PartnerCode'
        }
        /// <summary>
        /// Test the property 'AccNo'
        /// </summary>
        [Test]
        public void AccNoTest()
        {
            // TODO unit test for the property 'AccNo'
        }
        /// <summary>
        /// Test the property 'ClientIdNo'
        /// </summary>
        [Test]
        public void ClientIdNoTest()
        {
            // TODO unit test for the property 'ClientIdNo'
        }
        /// <summary>
        /// Test the property 'TransId'
        /// </summary>
        [Test]
        public void TransIdTest()
        {
            // TODO unit test for the property 'TransId'
        }
        /// <summary>
        /// Test the property 'TransAmount'
        /// </summary>
        [Test]
        public void TransAmountTest()
        {
            // TODO unit test for the property 'TransAmount'
        }
        /// <summary>
        /// Test the property 'TransTime'
        /// </summary>
        [Test]
        public void TransTimeTest()
        {
            // TODO unit test for the property 'TransTime'
        }
        /// <summary>
        /// Test the property 'BefTransDebt'
        /// </summary>
        [Test]
        public void BefTransDebtTest()
        {
            // TODO unit test for the property 'BefTransDebt'
        }
        /// <summary>
        /// Test the property 'AffTransDebt'
        /// </summary>
        [Test]
        public void AffTransDebtTest()
        {
            // TODO unit test for the property 'AffTransDebt'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Test]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Test]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

    }

}
