/* 
 * Collection payments
 *
 * <img src=\"https://devtest.baokim.vn/collection/core_ctt/image/Picture1.png\" class=\"image-collection-payment\" /> <p><strong>Note:</strong></p> <p>+ In case PARTNER want to use collect via Virtual Account, PARTNER will need to buid:</p> <p style=\"padding-left: 50px;\">     - <a href=\"#operations-Virtual_Account_4\\.0-8442c69ffbaf4b3677a52fa3ebcef6d4\">Register virtual account</a> <br>     - <a href=\"#operations-Virtual_Account_4\\.0-1796c61005edee3976097a607fe9dbaa\">Update virtual account informations</a> <br>     - <a href=\"#operations-tag-Notice_of_collection_transaction\">Notice of collection transaction</a> <br> </p>
 *
 * OpenAPI spec version: 2.3 and 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse200
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse200Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse200
        //private InlineResponse200 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse200
            //instance = new InlineResponse200();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse200
        /// </summary>
        [Test]
        public void InlineResponse200InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse200
            //Assert.IsInstanceOfType<InlineResponse200> (instance, "variable 'instance' is a InlineResponse200");
        }


        /// <summary>
        /// Test the property 'ResponseCode'
        /// </summary>
        [Test]
        public void ResponseCodeTest()
        {
            // TODO unit test for the property 'ResponseCode'
        }
        /// <summary>
        /// Test the property 'ResponseMessage'
        /// </summary>
        [Test]
        public void ResponseMessageTest()
        {
            // TODO unit test for the property 'ResponseMessage'
        }
        /// <summary>
        /// Test the property 'PartnerCode'
        /// </summary>
        [Test]
        public void PartnerCodeTest()
        {
            // TODO unit test for the property 'PartnerCode'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'CollectAmountMin'
        /// </summary>
        [Test]
        public void CollectAmountMinTest()
        {
            // TODO unit test for the property 'CollectAmountMin'
        }
        /// <summary>
        /// Test the property 'CollectAmountMax'
        /// </summary>
        [Test]
        public void CollectAmountMaxTest()
        {
            // TODO unit test for the property 'CollectAmountMax'
        }
        /// <summary>
        /// Test the property 'ExpireDate'
        /// </summary>
        [Test]
        public void ExpireDateTest()
        {
            // TODO unit test for the property 'ExpireDate'
        }
        /// <summary>
        /// Test the property 'AccountInfo'
        /// </summary>
        [Test]
        public void AccountInfoTest()
        {
            // TODO unit test for the property 'AccountInfo'
        }

    }

}
