# coding: utf-8

"""
     Installment docs API

    <a href='/baokim-firm-open-api-9050'>1: Function Check Installment Support </a>  <a href='/baokim-firm-open-api-9051'>2: Function Get Bank Loan Package </a>  <a href='/baokim-firm-open-api-9052'>3: Function Create Transaction </a>  <a href='/baokim-firm-open-api-9062'>4: Function Cancel order</a>  Private key and public key Baokim is currently using digital signature by RSA-SHA1  There are several ways to generate RSA key pairs.  Way 1:  Generate your RSA key pairs online: <a href=\"http://travistidwell.com/blog/2013/09/06/an-online-rsa-public-and-private-key-generator/\" target=\"_blank\">Generate now</a>  Way 2:  Using OpenSSL software for Windows:  Step 1: Download the software at:  http://slproweb.com/products/Win32OpenSSL.html. Partner should download the installer \"OpenSSL_Light-1_0_2k\". Then install in any directory, for example \"C:\\OpenSSLWin64\"  Step 2: Access \"C:\\OpenSSLWin64\\bin\" then open the command prompt. Type the command to declare the environment config.  set OPENSSL_CONF=C:\\OpenSSL-Win64\\bin\\openssl.cfg  Step 3: Generate private key and public key  openssl genrsa -aes256 -out c:\\opensslkeys\\partner\\partner_privatekey.pem 2048  openssl rsa –in c:\\opensslkeys\\partner\\partner_privatekey.pem -pubout >c:\\opensslkeys\\partner\\partner_publickey.pem  After successful pairing, Partner will send back to Baokim the public key to authenticate the signature that the Partner sends via the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse157(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'response_code': 'int',
        'response_message': 'str',
        'data': 'InlineResponse157Data',
        'signature': 'str'
    }

    attribute_map = {
        'response_code': 'ResponseCode',
        'response_message': 'ResponseMessage',
        'data': 'Data',
        'signature': 'Signature'
    }

    def __init__(self, response_code=None, response_message=None, data=None, signature=None):  # noqa: E501
        """InlineResponse157 - a model defined in Swagger"""  # noqa: E501
        self._response_code = None
        self._response_message = None
        self._data = None
        self._signature = None
        self.discriminator = None
        if response_code is not None:
            self.response_code = response_code
        if response_message is not None:
            self.response_message = response_message
        if data is not None:
            self.data = data
        if signature is not None:
            self.signature = signature

    @property
    def response_code(self):
        """Gets the response_code of this InlineResponse157.  # noqa: E501


        :return: The response_code of this InlineResponse157.  # noqa: E501
        :rtype: int
        """
        return self._response_code

    @response_code.setter
    def response_code(self, response_code):
        """Sets the response_code of this InlineResponse157.


        :param response_code: The response_code of this InlineResponse157.  # noqa: E501
        :type: int
        """

        self._response_code = response_code

    @property
    def response_message(self):
        """Gets the response_message of this InlineResponse157.  # noqa: E501


        :return: The response_message of this InlineResponse157.  # noqa: E501
        :rtype: str
        """
        return self._response_message

    @response_message.setter
    def response_message(self, response_message):
        """Sets the response_message of this InlineResponse157.


        :param response_message: The response_message of this InlineResponse157.  # noqa: E501
        :type: str
        """

        self._response_message = response_message

    @property
    def data(self):
        """Gets the data of this InlineResponse157.  # noqa: E501


        :return: The data of this InlineResponse157.  # noqa: E501
        :rtype: InlineResponse157Data
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this InlineResponse157.


        :param data: The data of this InlineResponse157.  # noqa: E501
        :type: InlineResponse157Data
        """

        self._data = data

    @property
    def signature(self):
        """Gets the signature of this InlineResponse157.  # noqa: E501


        :return: The signature of this InlineResponse157.  # noqa: E501
        :rtype: str
        """
        return self._signature

    @signature.setter
    def signature(self, signature):
        """Sets the signature of this InlineResponse157.


        :param signature: The signature of this InlineResponse157.  # noqa: E501
        :type: str
        """

        self._signature = signature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse157, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse157):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
