/*
 * Retail api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RetailCheckpartnerlimitBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-30T01:32:08.691Z[Etc/UTC]")
public class RetailCheckpartnerlimitBody {
  @SerializedName("RequestId")
  private String requestId = null;

  @SerializedName("RequestTime")
  private String requestTime = null;

  @SerializedName("PartnerCode")
  private String partnerCode = null;

  public RetailCheckpartnerlimitBody requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Unique code 
   * @return requestId
  **/
  @Schema(example = "BK16321291688141", description = "Unique code ")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public RetailCheckpartnerlimitBody requestTime(String requestTime) {
    this.requestTime = requestTime;
    return this;
  }

   /**
   * Time send the request from PARTNER , format: YYYY-MM-DD HH:MM:SS.
   * @return requestTime
  **/
  @Schema(example = "2022-01-24 10:59:46", description = "Time send the request from PARTNER , format: YYYY-MM-DD HH:MM:SS.")
  public String getRequestTime() {
    return requestTime;
  }

  public void setRequestTime(String requestTime) {
    this.requestTime = requestTime;
  }

  public RetailCheckpartnerlimitBody partnerCode(String partnerCode) {
    this.partnerCode = partnerCode;
    return this;
  }

   /**
   * Unique code BAOKIM provide
   * @return partnerCode
  **/
  @Schema(example = "BANLEBAOKIM", description = "Unique code BAOKIM provide")
  public String getPartnerCode() {
    return partnerCode;
  }

  public void setPartnerCode(String partnerCode) {
    this.partnerCode = partnerCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetailCheckpartnerlimitBody retailCheckpartnerlimitBody = (RetailCheckpartnerlimitBody) o;
    return Objects.equals(this.requestId, retailCheckpartnerlimitBody.requestId) &&
        Objects.equals(this.requestTime, retailCheckpartnerlimitBody.requestTime) &&
        Objects.equals(this.partnerCode, retailCheckpartnerlimitBody.partnerCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, requestTime, partnerCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetailCheckpartnerlimitBody {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    requestTime: ").append(toIndentedString(requestTime)).append("\n");
    sb.append("    partnerCode: ").append(toIndentedString(partnerCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
