# coding: utf-8

"""
    Retail api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.retail_checkpartnerlimit_body import RetailCheckpartnerlimitBody  # noqa: E501
from swagger_client.rest import ApiException


class TestRetailCheckpartnerlimitBody(unittest.TestCase):
    """RetailCheckpartnerlimitBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRetailCheckpartnerlimitBody(self):
        """Test RetailCheckpartnerlimitBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.retail_checkpartnerlimit_body.RetailCheckpartnerlimitBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
