# coding: utf-8

"""
    Retail api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.check_partner_limit_api import CHECKPARTNERLIMITApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCHECKPARTNERLIMITApi(unittest.TestCase):
    """CHECKPARTNERLIMITApi unit test stubs"""

    def setUp(self):
        self.api = CHECKPARTNERLIMITApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_retail_check_partner_limit_post(self):
        """Test case for api_retail_check_partner_limit_post

        CHECK PARTNER LIMIT  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
