# coding: utf-8

"""
    Example for response examples value

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.collection_v2_body import CollectionV2Body  # noqa: E501
from swagger_client.rest import ApiException


class TestCollectionV2Body(unittest.TestCase):
    """CollectionV2Body unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionV2Body(self):
        """Test CollectionV2Body"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.collection_v2_body.CollectionV2Body()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
