/*
 *  Installment docs API
 * <a href='/baokim-firm-open-api-9050'>1: Function Check Installment Support </a>  <a href='/baokim-firm-open-api-9051'>2: Function Get Bank Loan Package </a>  <a href='/baokim-firm-open-api-9052'>3: Function Create Transaction </a>  <a href='/baokim-firm-open-api-9062'>4: Function Cancel order</a>  Private key and public key Baokim is currently using digital signature by RSA-SHA1  There are several ways to generate RSA key pairs.  Way 1:  Generate your RSA key pairs online: <a href=\"http://travistidwell.com/blog/2013/09/06/an-online-rsa-public-and-private-key-generator/\" target=\"_blank\">Generate now</a>  Way 2:  Using OpenSSL software for Windows:  Step 1: Download the software at:  http://slproweb.com/products/Win32OpenSSL.html. Partner should download the installer \"OpenSSL_Light-1_0_2k\". Then install in any directory, for example \"C:\\OpenSSLWin64\"  Step 2: Access \"C:\\OpenSSLWin64\\bin\" then open the command prompt. Type the command to declare the environment config.  set OPENSSL_CONF=C:\\OpenSSL-Win64\\bin\\openssl.cfg  Step 3: Generate private key and public key  openssl genrsa -aes256 -out c:\\opensslkeys\\partner\\partner_privatekey.pem 2048  openssl rsa –in c:\\opensslkeys\\partner\\partner_privatekey.pem -pubout >c:\\opensslkeys\\partner\\partner_publickey.pem  After successful pairing, Partner will send back to Baokim the public key to authenticate the signature that the Partner sends via the API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse2001DataLoanPackages
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-30T01:29:43.937Z[Etc/UTC]")
public class InlineResponse2001DataLoanPackages {
  @SerializedName("LoanPackId")
  private String loanPackId = null;

  @SerializedName("PackageName")
  private String packageName = null;

  @SerializedName("GracePeriod")
  private String gracePeriod = null;

  @SerializedName("ConversionFee")
  private String conversionFee = null;

  public InlineResponse2001DataLoanPackages loanPackId(String loanPackId) {
    this.loanPackId = loanPackId;
    return this;
  }

   /**
   * Get loanPackId
   * @return loanPackId
  **/
  @Schema(example = "638", description = "")
  public String getLoanPackId() {
    return loanPackId;
  }

  public void setLoanPackId(String loanPackId) {
    this.loanPackId = loanPackId;
  }

  public InlineResponse2001DataLoanPackages packageName(String packageName) {
    this.packageName = packageName;
    return this;
  }

   /**
   * Get packageName
   * @return packageName
  **/
  @Schema(example = "Gói vay kỳ hạn 6 tháng", description = "")
  public String getPackageName() {
    return packageName;
  }

  public void setPackageName(String packageName) {
    this.packageName = packageName;
  }

  public InlineResponse2001DataLoanPackages gracePeriod(String gracePeriod) {
    this.gracePeriod = gracePeriod;
    return this;
  }

   /**
   * Get gracePeriod
   * @return gracePeriod
  **/
  @Schema(example = "6", description = "")
  public String getGracePeriod() {
    return gracePeriod;
  }

  public void setGracePeriod(String gracePeriod) {
    this.gracePeriod = gracePeriod;
  }

  public InlineResponse2001DataLoanPackages conversionFee(String conversionFee) {
    this.conversionFee = conversionFee;
    return this;
  }

   /**
   * Get conversionFee
   * @return conversionFee
  **/
  @Schema(example = "2.0", description = "")
  public String getConversionFee() {
    return conversionFee;
  }

  public void setConversionFee(String conversionFee) {
    this.conversionFee = conversionFee;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001DataLoanPackages inlineResponse2001DataLoanPackages = (InlineResponse2001DataLoanPackages) o;
    return Objects.equals(this.loanPackId, inlineResponse2001DataLoanPackages.loanPackId) &&
        Objects.equals(this.packageName, inlineResponse2001DataLoanPackages.packageName) &&
        Objects.equals(this.gracePeriod, inlineResponse2001DataLoanPackages.gracePeriod) &&
        Objects.equals(this.conversionFee, inlineResponse2001DataLoanPackages.conversionFee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loanPackId, packageName, gracePeriod, conversionFee);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001DataLoanPackages {\n");
    
    sb.append("    loanPackId: ").append(toIndentedString(loanPackId)).append("\n");
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("    gracePeriod: ").append(toIndentedString(gracePeriod)).append("\n");
    sb.append("    conversionFee: ").append(toIndentedString(conversionFee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
